# Generated by Django 3.0.3 on 2020-03-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200303_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='ride_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
