# Generated by Django 3.0.3 on 2020-03-02 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='is_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
