# Generated by Django 3.0.3 on 2020-03-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200303_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mobile',
        ),
    ]
