# Generated by Django 3.0.3 on 2020-03-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200303_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
