# Generated by Django 3.0.3 on 2020-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=60)),
                ('to', models.CharField(max_length=60)),
                ('Assigned_to', models.CharField(max_length=255)),
                ('Start_status', models.BooleanField(default=False)),
                ('Finish_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
