# Generated by Django 3.0.3 on 2020-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='ride_no',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
